apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
- target:
    group: source.toolkit.fluxcd.io
    version: v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/provider
      value: github
    - op: replace
      path: /spec/url
      value: https://github.com/${owner}/${repository}.git
